rules:
- id: dockerfile.best-practice.missing-dnf-assume-yes-switch.missing-dnf-assume-yes-switch
  severity: WARNING
  languages:
  - dockerfile
  patterns:
  - pattern: |
      RUN ... dnf install ...
  - pattern-not-inside: |
      RUN ... dnf install ... -y ...
  - pattern-not-inside: |
      RUN ... dnf ... --assumeyes ...
  message: This 'dnf install' is missing the '-y' switch. This might stall builds
    because it requires human intervention. Add the '-y' switch.
  metadata:
    source-rule-url: https://github.com/hadolint/hadolint/wiki/DL3038
    references:
    - https://github.com/hadolint/hadolint/wiki/DL3038
    category: best-practice
    technology:
    - dockerfile
    license: Commons Clause License Condition v1.0[LGPL-2.1-only]
    source: https://semgrep.dev/r/dockerfile.best-practice.missing-dnf-assume-yes-switch.missing-dnf-assume-yes-switch
    shortlink: https://sg.run/kD5K
    semgrep.dev:
      rule:
        r_id: 20128
        rv_id: 109235
        rule_id: x8Ud03
        version_id: qkT2xJd
        url: https://semgrep.dev/playground/r/qkT2xJd/dockerfile.best-practice.missing-dnf-assume-yes-switch.missing-dnf-assume-yes-switch
        origin: community
