rules:
- id: dockerfile.best-practice.missing-yum-assume-yes-switch.missing-yum-assume-yes-switch
  severity: WARNING
  languages:
  - dockerfile
  patterns:
  - pattern: |
      RUN ... yum install ...
  - pattern-not: |
      RUN ... yum install ... -y ...
  - pattern-not: |
      RUN ... yum ... --assumeyes ...
  message: This 'yum install' is missing the '-y' switch. This might stall builds
    because it requires human intervention. Add the '-y' switch.
  metadata:
    source-rule-url: https://github.com/hadolint/hadolint/wiki/DL3030
    references:
    - https://github.com/hadolint/hadolint/wiki/DL3030
    category: best-practice
    technology:
    - dockerfile
    license: Commons Clause License Condition v1.0[LGPL-2.1-only]
    source: https://semgrep.dev/r/dockerfile.best-practice.missing-yum-assume-yes-switch.missing-yum-assume-yes-switch
    shortlink: https://sg.run/vpY4
    semgrep.dev:
      rule:
        r_id: 20133
        rv_id: 109240
        rule_id: ZqUex1
        version_id: zyTK8rE
        url: https://semgrep.dev/playground/r/zyTK8rE/dockerfile.best-practice.missing-yum-assume-yes-switch.missing-yum-assume-yes-switch
        origin: community
