rules:
- id: dockerfile.best-practice.use-shell-instruction.use-shell-instruction
  severity: WARNING
  languages:
  - dockerfile
  pattern: |
    RUN ln ... $SHELL /bin/sh
  message: Use the SHELL instruction to set the default shell instead of overwriting
    '/bin/sh'.
  metadata:
    source-rule-url: https://github.com/hadolint/hadolint/wiki/DL4005
    references:
    - https://github.com/hadolint/hadolint/wiki/DL4005
    category: best-practice
    technology:
    - dockerfile
    license: Commons Clause License Condition v1.0[LGPL-2.1-only]
    source: https://semgrep.dev/r/dockerfile.best-practice.use-shell-instruction.use-shell-instruction
    shortlink: https://sg.run/3Qnb
    semgrep.dev:
      rule:
        r_id: 20143
        rv_id: 109250
        rule_id: PeUj2G
        version_id: NdT3dJO
        url: https://semgrep.dev/playground/r/NdT3dJO/dockerfile.best-practice.use-shell-instruction.use-shell-instruction
        origin: community
  fix: SHELL ["$SHELL", "-c"]
