rules:
- id: dockerfile.best-practice.prefer-json-notation.prefer-json-notation
  severity: INFO
  languages:
  - dockerfile
  message: Prefer JSON notation when using CMD or ENTRYPOINT. This allows signals
    to be passed from the OS.
  metadata:
    source-rule-url: https://github.com/hadolint/hadolint/wiki/DL3025
    references:
    - https://github.com/hadolint/hadolint/wiki/DL3025
    - https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#cmd
    category: best-practice
    technology:
    - dockerfile
    license: Commons Clause License Condition v1.0[LGPL-2.1-only]
    source: https://semgrep.dev/r/dockerfile.best-practice.prefer-json-notation.prefer-json-notation
    shortlink: https://sg.run/7QJR
    semgrep.dev:
      rule:
        r_id: 20138
        rv_id: 109245
        rule_id: 8GUvgR
        version_id: 1QTOYQv
        url: https://semgrep.dev/playground/r/1QTOYQv/dockerfile.best-practice.prefer-json-notation.prefer-json-notation
        origin: community
  pattern-either:
  - patterns:
    - pattern: CMD $WORD ...
    - pattern-not-inside: CMD [...]
  - patterns:
    - pattern: ENTRYPOINT $WORD ...
    - pattern-not-inside: ENTRYPOINT [...]
