rules:
- id: dockerfile.best-practice.maintainer-is-deprecated.maintainer-is-deprecated
  severity: INFO
  languages:
  - dockerfile
  pattern: MAINTAINER $NAME
  message: MAINTAINER has been deprecated.
  metadata:
    source-rule-url: https://github.com/hadolint/hadolint/wiki/DL4000
    references:
    - https://github.com/hadolint/hadolint/wiki/DL4000
    category: best-practice
    technology:
    - dockerfile
    license: Commons Clause License Condition v1.0[LGPL-2.1-only]
    source: https://semgrep.dev/r/dockerfile.best-practice.maintainer-is-deprecated.maintainer-is-deprecated
    shortlink: https://sg.run/bWKe
    semgrep.dev:
      rule:
        r_id: 20126
        rv_id: 109233
        rule_id: kxUO35
        version_id: 0bTLlqR
        url: https://semgrep.dev/playground/r/0bTLlqR/dockerfile.best-practice.maintainer-is-deprecated.maintainer-is-deprecated
        origin: community
  fix: '# MAINTAINER $NAME'
