rules:
- id: dockerfile.best-practice.missing-zypper-clean.missing-zypper-clean
  severity: WARNING
  languages:
  - dockerfile
  patterns:
  - pattern: RUN ... zypper $COMMAND ...
  - pattern-not-inside: RUN ... zypper clean
  - pattern-not-inside: RUN ... zypper clean
  message: This zypper command does not end with '&& zypper clean'. Running 'zypper
    clean' will remove cached data and reduce package size. (This must be performed
    in the same RUN step.)
  metadata:
    source-rule-url: https://github.com/hadolint/hadolint/wiki/DL3036
    references:
    - https://github.com/hadolint/hadolint/wiki/DL3036
    category: best-practice
    technology:
    - dockerfile
    license: Commons Clause License Condition v1.0[LGPL-2.1-only]
    source: https://semgrep.dev/r/dockerfile.best-practice.missing-zypper-clean.missing-zypper-clean
    shortlink: https://sg.run/dPlY
    semgrep.dev:
      rule:
        r_id: 20134
        rv_id: 109241
        rule_id: nJUnJ1
        version_id: pZT1yA7
        url: https://semgrep.dev/playground/r/pZT1yA7/dockerfile.best-practice.missing-zypper-clean.missing-zypper-clean
        origin: community
