rules:
- id: dockerfile.best-practice.avoid-platform-with-from.avoid-platform-with-from
  severity: INFO
  languages:
  - dockerfile
  pattern: FROM --platform=$PLATFORM $IMAGE
  message: Using '--platform' with FROM restricts the image to build on a single platform.
    Further, this must be the same as the build platform. If you intended to specify
    the target platform, use the utility 'docker buildx --platform=' instead.
  metadata:
    source-rule-url: https://github.com/hadolint/hadolint/wiki/DL3029
    references:
    - https://github.com/hadolint/hadolint/wiki/DL3029
    - https://docs.docker.com/buildx/working-with-buildx/
    category: best-practice
    technology:
    - dockerfile
    license: Commons Clause License Condition v1.0[LGPL-2.1-only]
    source: https://semgrep.dev/r/dockerfile.best-practice.avoid-platform-with-from.avoid-platform-with-from
    shortlink: https://sg.run/93G4
    semgrep.dev:
      rule:
        r_id: 20123
        rv_id: 109230
        rule_id: r6Ujl1
        version_id: BjTXrvo
        url: https://semgrep.dev/playground/r/BjTXrvo/dockerfile.best-practice.avoid-platform-with-from.avoid-platform-with-from
        origin: community
