rules:
- id: dockerfile.best-practice.remove-package-lists.remove-package-lists
  patterns:
  - pattern-not-inside: RUN ... rm -rf /var/lib/apt/lists/*
  - pattern: RUN apt-get update ...
  - pattern: apt-get update
  message: The package lists were not deleted after running 'apt-get update', which
    increases the size of the image. Remove the package lists by appending '&& rm
    -rf /var/lib/apt/lists/*' at the end of apt-get command chain.
  severity: WARNING
  languages:
  - dockerfile
  metadata:
    source-rule-url: https://github.com/hadolint/hadolint/wiki/DL3009
    references:
    - https://github.com/hadolint/hadolint/wiki/DL3009
    category: best-practice
    technology:
    - dockerfile
    license: Commons Clause License Condition v1.0[LGPL-2.1-only]
    source: https://semgrep.dev/r/dockerfile.best-practice.remove-package-lists.remove-package-lists
    shortlink: https://sg.run/8k57
    semgrep.dev:
      rule:
        r_id: 20140
        rv_id: 109247
        rule_id: QrU1Ax
        version_id: yeTR2eJ
        url: https://semgrep.dev/playground/r/yeTR2eJ/dockerfile.best-practice.remove-package-lists.remove-package-lists
        origin: community
