id: dockerfile.best-practice.avoid-zypper-update.avoid-zypper-update
severity: INFO
languages:
- dockerfile
message: Packages in base images should be up-to-date, removing the need for 'zypper
  update'. If packages are out-of-date, consider contacting the base image maintainer.
metadata:
  source-rule-url: https://github.com/hadolint/hadolint/wiki/DL3035
  references:
  - https://github.com/hadolint/hadolint/wiki/DL3035
  category: best-practice
  technology:
  - dockerfile
  license: Commons Clause License Condition v1.0[LGPL-2.1-only]
  source: https://semgrep.dev/r/dockerfile.best-practice.avoid-zypper-update.avoid-zypper-update
  shortlink: https://sg.run/rN00
  semgrep.dev:
    rule:
      r_id: 20125
      rv_id: 109232
      rule_id: NbUeGG
      version_id: WrTWQJ5
      url: https://semgrep.dev/playground/r/WrTWQJ5/dockerfile.best-practice.avoid-zypper-update.avoid-zypper-update
      origin: community
pattern: zypper update ...
