id: dockerfile.best-practice.missing-no-install-recommends.missing-no-install-recommends
patterns:
- pattern: 'RUN apt-get install ...

    '
- pattern-not: RUN apt-get install ... --no-install-recommends ...
languages:
- dockerfile
message: This 'apt-get install' is missing '--no-install-recommends'. This prevents
  unnecessary packages from being installed, thereby reducing image size. Add '--no-install-recommends'.
severity: INFO
metadata:
  source-rule-url: https://github.com/hadolint/hadolint/wiki/DL3015
  references:
  - https://github.com/hadolint/hadolint/wiki/DL3015
  category: best-practice
  technology:
  - dockerfile
  license: Commons Clause License Condition v1.0[LGPL-2.1-only]
  source: https://semgrep.dev/r/dockerfile.best-practice.missing-no-install-recommends.missing-no-install-recommends
  shortlink: https://sg.run/O4dp
  semgrep.dev:
    rule:
      r_id: 20131
      rv_id: 109238
      rule_id: v8UvoK
      version_id: 6xTvJWn
      url: https://semgrep.dev/playground/r/6xTvJWn/dockerfile.best-practice.missing-no-install-recommends.missing-no-install-recommends
      origin: community
