id: dockerfile.best-practice.prefer-apt-get.prefer-apt-get
severity: INFO
languages:
- dockerfile
patterns:
- pattern: RUN apt ...
- pattern-not: RUN apt-get ...
message: '''apt-get'' is preferred as an unattended tool for stability. ''apt'' is
  discouraged.'
metadata:
  source-rule-url: https://github.com/hadolint/hadolint/wiki/DL3027
  references:
  - https://github.com/hadolint/hadolint/wiki/DL3027
  category: best-practice
  technology:
  - dockerfile
  license: Commons Clause License Condition v1.0[LGPL-2.1-only]
  source: https://semgrep.dev/r/dockerfile.best-practice.prefer-apt-get.prefer-apt-get
  shortlink: https://sg.run/nwAO
  semgrep.dev:
    rule:
      r_id: 20136
      rv_id: 109243
      rule_id: 7KUbZG
      version_id: X0TQxnK
      url: https://semgrep.dev/playground/r/X0TQxnK/dockerfile.best-practice.prefer-apt-get.prefer-apt-get
      origin: community
