id: dockerfile.best-practice.missing-image-version.missing-image-version
patterns:
- pattern-either:
  - pattern: FROM $IMAGE
- pattern-not: FROM $IMAGE:$VERSION
- pattern-not: FROM $IMAGE@$DIGEST
- pattern-not: FROM $IMAGE:$VERSION@$DIGEST
- pattern-not: FROM scratch
message: Detected docker image with no explicit version attached. Images should be
  tagged with an explicit version to produce deterministic container images -- attach
  a version when using  `FROM <image>`.
severity: WARNING
languages:
- dockerfile
metadata:
  source-rule-url: https://github.com/hadolint/hadolint/wiki/DL3006
  references:
  - https://github.com/hadolint/hadolint/wiki/DL3006
  category: best-practice
  technology:
  - dockerfile
  license: Commons Clause License Condition v1.0[LGPL-2.1-only]
  source: https://semgrep.dev/r/dockerfile.best-practice.missing-image-version.missing-image-version
  shortlink: https://sg.run/xPop
  semgrep.dev:
    rule:
      r_id: 20130
      rv_id: 109237
      rule_id: eqUZbw
      version_id: YDTp245
      url: https://semgrep.dev/playground/r/YDTp245/dockerfile.best-practice.missing-image-version.missing-image-version
      origin: community
