id: dockerfile.best-practice.remove-package-cache.remove-package-cache
patterns:
- pattern-not-inside: RUN ... && apt-get clean ...
- pattern: RUN ... apt-get update ...
- pattern: apt-get update
message: The package cache was not deleted after running 'apt-get update', which increases
  the size of the image. Remove the package cache by appending '&& apt-get clean'
  at the end of apt-get command chain.
severity: WARNING
languages:
- dockerfile
metadata:
  source-rule-url: https://github.com/hadolint/hadolint/wiki/DL3009
  references:
  - https://github.com/hadolint/hadolint/wiki/DL3009
  category: best-practice
  technology:
  - dockerfile
  license: Commons Clause License Condition v1.0[LGPL-2.1-only]
  source: https://semgrep.dev/r/dockerfile.best-practice.remove-package-cache.remove-package-cache
  shortlink: https://sg.run/L2vJ
  semgrep.dev:
    rule:
      r_id: 20139
      rv_id: 109246
      rule_id: gxUkEK
      version_id: 9lTdW6B
      url: https://semgrep.dev/playground/r/9lTdW6B/dockerfile.best-practice.remove-package-cache.remove-package-cache
      origin: community
