id: dockerfile.best-practice.use-either-wget-or-curl.use-either-wget-or-curl
severity: INFO
languages:
- dockerfile
message: '''wget'' and ''curl'' are similar tools. Choose one and do not install the
  other to decrease image size.'
metadata:
  source-rule-url: https://github.com/hadolint/hadolint/wiki/DL4001
  references:
  - https://github.com/hadolint/hadolint/wiki/DL4001
  category: best-practice
  technology:
  - dockerfile
  license: Commons Clause License Condition v1.0[LGPL-2.1-only]
  source: https://semgrep.dev/r/dockerfile.best-practice.use-either-wget-or-curl.use-either-wget-or-curl
  shortlink: https://sg.run/QJ3P
  semgrep.dev:
    rule:
      r_id: 20142
      rv_id: 109249
      rule_id: 4bUe5P
      version_id: bZTb1lG
      url: https://semgrep.dev/playground/r/bZTb1lG/dockerfile.best-practice.use-either-wget-or-curl.use-either-wget-or-curl
      origin: community
pattern-either:
- pattern: 'RUN wget ...

    ...

    RUN curl ...

    '
- pattern: 'RUN curl ...

    ...

    RUN wget ...

    '
