id: dockerfile.security.missing-user.missing-user
patterns:
- pattern: 'CMD $...VARS

    '
- pattern-not-inside: 'USER $USER

    ...

    '
fix: 'USER non-root

  CMD $...VARS

  '
message: By not specifying a USER, a program in the container may run as 'root'. This
  is a security hazard. If an attacker can control a process running as root, they
  may have control over the container. Ensure that the last USER in a Dockerfile is
  a USER other than 'root'.
severity: ERROR
languages:
- dockerfile
metadata:
  cwe:
  - 'CWE-269: Improper Privilege Management'
  category: security
  technology:
  - dockerfile
  confidence: MEDIUM
  owasp:
  - A04:2021 - Insecure Design
  references:
  - https://owasp.org/Top10/A04_2021-Insecure_Design
  subcategory:
  - audit
  likelihood: LOW
  impact: MEDIUM
  license: Commons Clause License Condition v1.0[LGPL-2.1-only]
  vulnerability_class:
  - Improper Authorization
  source: https://semgrep.dev/r/dockerfile.security.missing-user.missing-user
  shortlink: https://sg.run/Gbvn
  semgrep.dev:
    rule:
      r_id: 20148
      rv_id: 109257
      rule_id: AbUN06
      version_id: d6TrApz
      url: https://semgrep.dev/playground/r/d6TrApz/dockerfile.security.missing-user.missing-user
      origin: community
