id: dockerfile.correctness.invalid-port.invalid-port
message: Detected an invalid port number. Valid ports are 0 through 65535.
severity: ERROR
languages:
- dockerfile
metadata:
  source-rule-url: https://github.com/hadolint/hadolint/wiki/DL3011
  references:
  - https://github.com/hadolint/hadolint/wiki/DL3011
  category: correctness
  technology:
  - dockerfile
  license: Commons Clause License Condition v1.0[LGPL-2.1-only]
  source: https://semgrep.dev/r/dockerfile.correctness.invalid-port.invalid-port
  shortlink: https://sg.run/w4Ex
  semgrep.dev:
    rule:
      r_id: 20729
      rv_id: 109252
      rule_id: r6UjWk
      version_id: w8T9ny1
      url: https://semgrep.dev/playground/r/w8T9ny1/dockerfile.correctness.invalid-port.invalid-port
      origin: community
pattern-either:
- patterns:
  - pattern: EXPOSE $PORT
  - metavariable-comparison:
      metavariable: $PORT
      comparison: int($PORT) > 65535
