id: dockerfile.best-practice.nonsensical-command.nonsensical-command
patterns:
- pattern: RUN $CMD ...
- metavariable-regex:
    metavariable: $CMD
    regex: (shutdown|service|ps|free|top|kill|mount|ifconfig|nano|vim)
message: Some commands such as `$CMD` do not make sense in a container. Do not use
  these.
severity: WARNING
languages:
- dockerfile
metadata:
  source-rule-url: https://github.com/hadolint/hadolint/wiki/DL3001
  references:
  - https://github.com/hadolint/hadolint/wiki/DL3001
  category: best-practice
  technology:
  - dockerfile
  license: Commons Clause License Condition v1.0[LGPL-2.1-only]
  source: https://semgrep.dev/r/dockerfile.best-practice.nonsensical-command.nonsensical-command
  shortlink: https://sg.run/ZP5n
  semgrep.dev:
    rule:
      r_id: 20135
      rv_id: 109242
      rule_id: EwU1vL
      version_id: 2KTzrEx
      url: https://semgrep.dev/playground/r/2KTzrEx/dockerfile.best-practice.nonsensical-command.nonsensical-command
      origin: community
