id: dockerfile.best-practice.set-pipefail.set-pipefail
languages:
- dockerfile
message: Only the exit code from the final command in this RUN instruction will be
  evaluated unless 'pipefail' is set. If you want to fail the command at any stage
  in the pipe, set 'pipefail' by including 'SHELL ["/bin/bash", "-o", "pipefail",
  "-c"] before the command. If you're using alpine and don't have bash installed,
  communicate this explicitly with `SHELL ["/bin/ash"]`.
metadata:
  references:
  - https://github.com/hadolint/hadolint/wiki/DL4006
  source-rule-url: https://github.com/hadolint/hadolint/wiki/DL4006
  category: best-practice
  technology:
  - dockerfile
  license: Commons Clause License Condition v1.0[LGPL-2.1-only]
  source: https://semgrep.dev/r/dockerfile.best-practice.set-pipefail.set-pipefail
  shortlink: https://sg.run/gGon
  semgrep.dev:
    rule:
      r_id: 20141
      rv_id: 109248
      rule_id: 3qULW0
      version_id: rxTyLN5
      url: https://semgrep.dev/playground/r/rxTyLN5/dockerfile.best-practice.set-pipefail.set-pipefail
      origin: community
patterns:
- pattern-either:
  - pattern: RUN ... | ...
  - pattern: RUN ... || ...
- pattern-not-inside: 'SHELL [..., "pipefail", ...]

    ...

    RUN ... | ...

    '
- pattern-not-inside: 'SHELL ["/bin/ash", ...]

    ...

    RUN ... | ...

    '
severity: WARNING
