id: javascript.browser.security.wildcard-postmessage-configuration.wildcard-postmessage-configuration
message: The target origin of the window.postMessage() API is set to "*". This could
  allow for information disclosure due to the possibility of any origin allowed to
  receive the message.
metadata:
  owasp:
  - A08:2021 - Software and Data Integrity Failures
  cwe:
  - 'CWE-345: Insufficient Verification of Data Authenticity'
  category: security
  technology:
  - browser
  subcategory:
  - audit
  likelihood: HIGH
  impact: MEDIUM
  confidence: MEDIUM
  references:
  - https://owasp.org/Top10/A08_2021-Software_and_Data_Integrity_Failures
  license: Commons Clause License Condition v1.0[LGPL-2.1-only]
  vulnerability_class:
  - Improper Authentication
  source: https://semgrep.dev/r/javascript.browser.security.wildcard-postmessage-configuration.wildcard-postmessage-configuration
  shortlink: https://sg.run/PJ4p
  semgrep.dev:
    rule:
      r_id: 9245
      rv_id: 109824
      rule_id: KxUbq4
      version_id: LjTqQvN
      url: https://semgrep.dev/playground/r/LjTqQvN/javascript.browser.security.wildcard-postmessage-configuration.wildcard-postmessage-configuration
      origin: community
languages:
- javascript
- typescript
severity: WARNING
pattern: $OBJECT.postMessage(...,'*')
