id: javascript.express.security.audit.express-cookie-settings.express-cookie-session-no-expires
message: 'Default session middleware settings: `expires` not set. Use it to set expiration
  date for persistent cookies.'
severity: WARNING
languages:
- javascript
- typescript
metadata:
  cwe:
  - 'CWE-522: Insufficiently Protected Credentials'
  owasp:
  - A02:2017 - Broken Authentication
  - A04:2021 - Insecure Design
  source-rule-url: https://expressjs.com/en/advanced/best-practice-security.html
  category: security
  technology:
  - express
  cwe2021-top25: true
  subcategory:
  - vuln
  likelihood: HIGH
  impact: LOW
  confidence: MEDIUM
  references:
  - https://owasp.org/Top10/A04_2021-Insecure_Design
  license: Commons Clause License Condition v1.0[LGPL-2.1-only]
  vulnerability_class:
  - Cryptographic Issues
  source: https://semgrep.dev/r/javascript.express.security.audit.express-cookie-settings.express-cookie-session-no-expires
  shortlink: https://sg.run/N4eG
  semgrep.dev:
    rule:
      r_id: 9271
      rv_id: 109839
      rule_id: EwU2DZ
      version_id: 0bTLljo
      url: https://semgrep.dev/playground/r/0bTLljo/javascript.express.security.audit.express-cookie-settings.express-cookie-session-no-expires
      origin: community
patterns:
- pattern-either:
  - pattern-inside: '$SESSION = require(''cookie-session'');

      ...

      '
  - pattern-inside: '$SESSION = require(''express-session'');

      ...

      '
- pattern: $SESSION(...)
- pattern-not-inside: $SESSION(<... {cookie:{expires:...}} ...>,...)
- pattern-not-inside: '$OPTS = <... {cookie:{expires:...}} ...>;

    ...

    $SESSION($OPTS,...);

    '
- pattern-not-inside: '$OPTS = ...;

    ...

    $COOKIE = <... {expires:...} ...>;

    ...

    $SESSION($OPTS,...);

    '
- pattern-not-inside: '$OPTS = ...;

    ...

    $OPTS.cookie = <... {expires:...} ...>;

    ...

    $SESSION($OPTS,...);

    '
- pattern-not-inside: '$OPTS = ...;

    ...

    $COOKIE.expires = ...;

    ...

    $SESSION($OPTS,...);

    '
- pattern-not-inside: '$OPTS = ...;

    ...

    $OPTS.cookie.expires = ...;

    ...

    $SESSION($OPTS,...);'
