id: python.distributed.security.require-encryption
patterns:
- pattern: 'distributed.security.Security(..., require_encryption=$VAL, ...)

    '
- metavariable-pattern:
    metavariable: $VAL
    pattern: 'False

      '
- focus-metavariable: $VAL
fix: 'True

  '
message: Initializing a security context for Dask (`distributed`) without "require_encryption"
  keyword argument may silently fail to provide security.
severity: WARNING
metadata:
  cwe:
  - 'CWE-319: Cleartext Transmission of Sensitive Information'
  owasp:
  - A03:2017 - Sensitive Data Exposure
  - A02:2021 - Cryptographic Failures
  references:
  - https://distributed.dask.org/en/latest/tls.html?highlight=require_encryption#parameters
  category: security
  technology:
  - distributed
  subcategory:
  - vuln
  likelihood: MEDIUM
  impact: MEDIUM
  confidence: MEDIUM
  license: Commons Clause License Condition v1.0[LGPL-2.1-only]
  vulnerability_class:
  - Mishandled Sensitive Information
  source: https://semgrep.dev/r/python.distributed.security.require-encryption
  shortlink: https://sg.run/AvQ2
  semgrep.dev:
    rule:
      r_id: 9450
      rv_id: 110159
      rule_id: YGURy0
      version_id: NdT3d8K
      url: https://semgrep.dev/playground/r/NdT3d8K/python.distributed.security.require-encryption
      origin: community
languages:
- python
