id: python.flask.web.flask-cookie-app-config-samesite-none.flask-cookie-app-config-samesite-none
message: 'Detected a cookie options with the `SameSite` flag set to "None". This is
  a potential security risk that arises from the way web browsers manage cookies.
  In a typical web application, cookies are used to store and transmit session-related
  data between a client and a server. To enhance security, cookies can be marked with
  the "SameSite" attribute, which restricts their usage based on the origin of the
  page that set them. This attribute can have three values: "Strict," "Lax," or "None".
  Make sure the `SameSite` attribute of the important cookies (e.g., session cookie)
  is set to a reasonable value. When `SameSite` is set to "Strict", no 3rd party cookie
  will be sent with outgoing requests, this is the most secure and private setting
  but harder to deploy with good usability. Setting it to "Lax" is the minimum requirement.'
severity: INFO
metadata:
  likelihood: LOW
  impact: LOW
  confidence: HIGH
  category: security
  subcategory:
  - vuln
  cwe:
  - 'CWE-1275: Sensitive Cookie with Improper SameSite Attribute'
  functional-categories:
  - web::search::cookie-config::flask
  - web::search::cookie-config::flask-jwt-extended
  - web::search::cookie-config::flask-login
  - web::search::cookie-config::flask-session
  owasp:
  - A01:2021 - Broken Access Control
  references:
  - https://owasp.org/Top10/A01_2021-Broken_Access_Control
  - https://web.dev/articles/samesite-cookies-explained
  technology:
  - cookie
  - cookies
  - flask
  - web
  license: Copyright 2023 Semgrep, Inc.
  vulnerability_class:
  - Cookie Security
  source: https://semgrep.dev/r/python.flask.web.flask-cookie-app-config-samesite-none.flask-cookie-app-config-samesite-none
  shortlink: https://sg.run/Nb9wL
  semgrep.dev:
    rule:
      r_id: 116527
      rv_id: 731977
      rule_id: OrUNQl8
      version_id: e1Tr2LO
      url: https://semgrep.dev/playground/r/e1Tr2LO/python.flask.web.flask-cookie-app-config-samesite-none.flask-cookie-app-config-samesite-none
      origin: pro_rules
languages:
- python
fix: '''Strict''

  '
options:
  symbolic_propagation: true
patterns:
- patterns:
  - pattern-either:
    - pattern: $APP.config["$SESSION_COOKIE_SAMESITE"] = $NONE
    - pattern: $APP.config.$SESSION_COOKIE_SAMESITE = $NONE
    - patterns:
      - pattern: "$APP.config.$UPDATE(\n  ...,\n  $SESSION_COOKIE_SAMESITE = $NONE,\n\
          \  ...\n)\n"
      - pattern-not-inside: "$APP.config.$UPDATE(\n    ...,\n    TESTING=True,\n \
          \   ...\n)\n"
      - pattern-not-inside: "$APP.config.$UPDATE(\n    ...,\n    DEBUG=True,\n   \
          \ ...\n)\n"
      - metavariable-regex:
          metavariable: $UPDATE
          regex: ^(update|from_mapping)$
    - pattern: '$OBJ = $CLASS()

        ...

        $OBJ.$SESSION_COOKIE_SAMESITE = $NONE

        ...

        $APP.config.from_object($OBJ, ...)

        '
    - pattern: '$SESSION_COOKIE_SAMESITE = $NONE

        ...

        $APP.config.from_object(__name__)

        '
  - metavariable-regex:
      metavariable: $SESSION_COOKIE_SAMESITE
      regex: ^(SESSION|REMEMBER|JWT)_COOKIE_SAMESITE$
  - metavariable-regex:
      metavariable: $NONE
      regex: ^("None")$
  - focus-metavariable: $NONE
