id: scala.play.security.conf-insecure-cookie-settings.conf-insecure-cookie-settings
patterns:
- pattern: secure = false
- pattern-inside: "session = {\n  ...\n}\n"
message: Session cookie `Secure` flag is explicitly disabled. The `secure` flag for
  cookies prevents the client from transmitting the cookie over insecure channels
  such as HTTP. Set the `Secure` flag by setting `secure` to `true` in configuration
  file.
languages:
- generic
severity: WARNING
paths:
  include:
  - '*.conf'
metadata:
  category: security
  references:
  - https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies#security
  - https://www.playframework.com/documentation/2.8.x/SettingsSession#Session-Configuration
  technology:
  - play
  - scala
  cwe:
  - 'CWE-614: Sensitive Cookie in HTTPS Session Without ''Secure'' Attribute'
  owasp:
  - A05:2021 - Security Misconfiguration
  confidence: MEDIUM
  subcategory:
  - vuln
  likelihood: LOW
  impact: LOW
  license: Commons Clause License Condition v1.0[LGPL-2.1-only]
  vulnerability_class:
  - Cookie Security
  source: https://semgrep.dev/r/scala.play.security.conf-insecure-cookie-settings.conf-insecure-cookie-settings
  shortlink: https://sg.run/8z8N
  semgrep.dev:
    rule:
      r_id: 18284
      rv_id: 110641
      rule_id: GdUDJO
      version_id: GxTv8Z5
      url: https://semgrep.dev/playground/r/GxTv8Z5/scala.play.security.conf-insecure-cookie-settings.conf-insecure-cookie-settings
      origin: community
