id: terraform.gcp.security.gcp-gke-private-cluster-config.gcp-gke-private-cluster-config
patterns:
- pattern: resource
- pattern-inside: 'resource "google_container_cluster" "..." {

    ...

    }

    '
- pattern-not-inside: "resource \"google_container_cluster\" \"...\" {\n...\nprivate_cluster_config\
    \ {\n  ...\n}\n...\n}\n"
message: Ensure Kubernetes Cluster is created with Private cluster enabled
metadata:
  owasp:
  - A05:2017 - Broken Access Control
  - A01:2021 - Broken Access Control
  cwe:
  - 'CWE-284: Improper Access Control'
  category: security
  technology:
  - terraform
  - gcp
  references:
  - https://owasp.org/Top10/A01_2021-Broken_Access_Control
  subcategory:
  - audit
  likelihood: LOW
  impact: LOW
  confidence: LOW
  license: Commons Clause License Condition v1.0[LGPL-2.1-only]
  vulnerability_class:
  - Improper Authorization
  source: https://semgrep.dev/r/terraform.gcp.security.gcp-gke-private-cluster-config.gcp-gke-private-cluster-config
  shortlink: https://sg.run/4XX5
  semgrep.dev:
    rule:
      r_id: 33688
      rv_id: 111015
      rule_id: qNULLE
      version_id: pZT1Ln6
      url: https://semgrep.dev/playground/r/pZT1Ln6/terraform.gcp.security.gcp-gke-private-cluster-config.gcp-gke-private-cluster-config
      origin: community
languages:
- hcl
severity: WARNING
