id: terraform.azure.best-practice.azure-keyvault-enables-firewall-rules-settings.azure-keyvault-enables-firewall-rules-settings
message: Ensure that key vault allows firewall rules settings
patterns:
- pattern: resource
- pattern-not-inside: "resource \"azurerm_key_vault\" \"...\" {\n...\nnetwork_acls\
    \ {\n  ...\n  default_action = \"Deny\"\n  ...\n}\n...\n}\n"
- pattern-inside: 'resource "azurerm_key_vault" "..." {

    ...

    }

    '
metadata:
  category: best-practice
  technology:
  - terraform
  - azure
  license: Commons Clause License Condition v1.0[LGPL-2.1-only]
  source: https://semgrep.dev/r/terraform.azure.best-practice.azure-keyvault-enables-firewall-rules-settings.azure-keyvault-enables-firewall-rules-settings
  shortlink: https://sg.run/9n4Y
  semgrep.dev:
    rule:
      r_id: 23923
      rv_id: 110827
      rule_id: 4bUl9D
      version_id: e1T03ZK
      url: https://semgrep.dev/playground/r/e1T03ZK/terraform.azure.best-practice.azure-keyvault-enables-firewall-rules-settings.azure-keyvault-enables-firewall-rules-settings
      origin: community
languages:
- hcl
severity: WARNING
