id: terraform.aws.security.aws-network-acl-allows-public-ingress.aws-network-acl-allows-public-ingress
patterns:
- pattern-either:
  - patterns:
    - pattern: "resource \"aws_network_acl_rule\" $ANYTHING {\n  ...\n  rule_action\
        \ = \"allow\"\n  cidr_block = \"$PUBLIC_IPV4_CIDR\"\n  ...\n}\n"
    - pattern-not: "resource \"aws_network_acl_rule\" $ANYTHING {\n  ...\n  egress\
        \ = true\n  ...\n}\n"
  - patterns:
    - pattern-inside: "resource \"$NETWORK_ACL\" $ANYTHING {\n  ...\n}\n"
    - pattern: "ingress {\n  ...\n  action = \"allow\"\n  cidr_block = \"$PUBLIC_IPV4_CIDR\"\
        \n  ...\n}\n"
    - metavariable-regex:
        metavariable: $NETWORK_ACL
        regex: ^(aws_network_acl|aws_default_network_acl)$
- metavariable-pattern:
    metavariable: $PUBLIC_IPV4_CIDR
    language: generic
    patterns:
    - pattern-not-regex: ^127\.\d{1,3}\.\d{1,3}\.\d{1,3}/(8|9|[1-3][0-9])$
    - pattern-not-regex: ^10\.\d{1,3}\.\d{1,3}\.\d{1,3}/(8|9|[1-3][0-9])$
    - pattern-not-regex: ^172\.(1[6-9]|2[0-9]|3[01])\.\d{1,3}\.\d{1,3}/(1[2-9]|[23][0-9])$
    - pattern-not-regex: ^192\.168\.\d{1,3}\.\d{1,3}/(1[6-9]|[23][0-9])$
    - pattern-not-regex: ^169\.254\.\d{1,3}\.\d{1,3}/(1[6-9]|[23][0-9])$
    - pattern-not-regex: ^100\.(6[4-9]|[7-9][0-9]|1[01][0-9]|12[0-7])\.\d{1,3}\.\d{1,3}/[1-3][0-9]$
    - pattern-not-regex: ^\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}/32$
message: The network ACL rule allows ingress from public internet. Opening up ACLs
  to the public internet is potentially dangerous. You should restrict access to IP
  addresses or ranges that explicitly require it where possible. Set a more restrictive
  CIDR range.
languages:
- hcl
severity: WARNING
metadata:
  category: security
  technology:
  - terraform
  - aws
  owasp:
  - A01:2021 - Broken Access Control
  cwe:
  - 'CWE-284: Improper Access Control'
  references:
  - https://owasp.org/Top10/A01_2021-Broken_Access_Control/
  - https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/network_acl
  - https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/network_acl_rule#cidr_block
  - https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/default_network_acl#cidr_block
  - https://docs.aws.amazon.com/vpc/latest/userguide/vpc-network-acls.html
  subcategory:
  - audit
  likelihood: MEDIUM
  impact: MEDIUM
  confidence: LOW
  license: Commons Clause License Condition v1.0[LGPL-2.1-only]
  vulnerability_class:
  - Improper Authorization
  source: https://semgrep.dev/r/terraform.aws.security.aws-network-acl-allows-public-ingress.aws-network-acl-allows-public-ingress
  shortlink: https://sg.run/bAdr
  semgrep.dev:
    rule:
      r_id: 57470
      rv_id: 110781
      rule_id: JDUb0Q
      version_id: 3ZTkr30
      url: https://semgrep.dev/playground/r/3ZTkr30/terraform.aws.security.aws-network-acl-allows-public-ingress.aws-network-acl-allows-public-ingress
      origin: community
