id: trailofbits.yaml.docker-compose.port-all-interfaces.port-all-interfaces
message: Service port is exposed on all interfaces
languages:
- yaml
severity: WARNING
metadata:
  category: security
  cwe: 'CWE-1327: Binding to an Unrestricted IP Address'
  subcategory:
  - audit
  technology:
  - docker
  - compose
  confidence: LOW
  likelihood: LOW
  impact: LOW
  references:
  - https://docs.docker.com/compose/compose-file/compose-file-v3/#ports
  license: AGPL-3.0 license
  vulnerability_class:
  - Other
  source: https://semgrep.dev/r/trailofbits.yaml.docker-compose.port-all-interfaces.port-all-interfaces
  shortlink: https://sg.run/gxAyK
  semgrep.dev:
    rule:
      r_id: 113241
      rv_id: 253312
      rule_id: j2UgnLW
      version_id: A8TkY2z
      url: https://semgrep.dev/playground/r/A8TkY2z/trailofbits.yaml.docker-compose.port-all-interfaces.port-all-interfaces
      origin: community
patterns:
- pattern-inside: "services:\n  ...\n"
- pattern: "ports:\n  - ...\n  - \"$PORT\"\n  - ...\n"
- focus-metavariable: $PORT
- metavariable-regex:
    metavariable: $PORT
    regex: ^(?!127.\d{1,3}.\d{1,3}.\d{1,3}:).+
