id: trailofbits.yaml.ansible.dnf-unencrypted-url.dnf-unencrypted-url
message: Found dnf download with unencrypted URL (e.g. HTTP, FTP, etc.)
languages:
- yaml
severity: WARNING
metadata:
  category: security
  cwe: 'CWE-319: Cleartext Transmission of Sensitive Information'
  subcategory:
  - audit
  technology:
  - ansible
  - dnf
  confidence: HIGH
  likelihood: HIGH
  impact: HIGH
  references:
  - https://docs.ansible.com/ansible/latest/collections/ansible/builtin/dnf_module.html#parameter-name
  - https://docs.ansible.com/ansible/latest/collections/ansible/builtin/dnf5_module.html#parameter-name
  license: AGPL-3.0 license
  vulnerability_class:
  - Mishandled Sensitive Information
  source: https://semgrep.dev/r/trailofbits.yaml.ansible.dnf-unencrypted-url.dnf-unencrypted-url
  shortlink: https://sg.run/kx0y1
  semgrep.dev:
    rule:
      r_id: 113228
      rv_id: 253299
      rule_id: DbU6R3w
      version_id: A8TkYdl
      url: https://semgrep.dev/playground/r/A8TkYdl/trailofbits.yaml.ansible.dnf-unencrypted-url.dnf-unencrypted-url
      origin: community
patterns:
- pattern-inside: "$DNF:\n  ...\n"
- metavariable-pattern:
    metavariable: $DNF
    pattern-either:
    - pattern: dnf
    - pattern: ansible.builtin.dnf
    - pattern: dnf5
    - pattern: ansible.builtin.dnf5
- pattern: '$KEY: ''$VALUE'''
- metavariable-pattern:
    metavariable: $KEY
    pattern-either:
    - pattern: name
    - pattern: pkg
- metavariable-regex:
    metavariable: $VALUE
    regex: (?i)^(http|ftp)://.*
