id: yaml.docker-compose.security.exposing-docker-socket-volume.exposing-docker-socket-volume
patterns:
- pattern-inside: 'version: ...

    ...

    '
- pattern-either:
  - pattern: "volumes:\n  - ...\n  - /var/run/docker.sock:/var/run/docker.sock\n \
      \ - ...\n"
  - pattern: "volumes:\n  - ...\n  - /run/docker.sock:/run/docker.sock\n  - ...\n"
  - pattern: "volumes:\n  - ...\n  - /var/run/docker.sock:/run/docker.sock\n  - ...\n"
  - pattern: "volumes:\n  - ...\n  - /run/docker.sock:/var/run/docker.sock\n  - ...\n"
  - pattern: "volumes:\n  - ...\n  - /var/run/docker.sock\n  - ...\n"
  - pattern: "volumes:\n  - ...\n  - /run/docker.sock\n  - ...\n"
  - pattern: "volumes:\n  - ...\n  - ...\n    source: /var/run/docker.sock\n    ...\n\
      \  - ...\n"
  - pattern: "volumes:\n  - ...\n  - ...\n    source: /run/docker.sock\n    ...\n\
      \  - ...\n"
message: Exposing host's Docker socket to containers via a volume. The owner of this
  socket is root. Giving someone access to it is equivalent to giving unrestricted
  root access to your host. Remove 'docker.sock' from volumes to prevent this.
metadata:
  references:
  - https://docs.docker.com/compose/compose-file/compose-file-v3/#volume-configuration-reference
  - https://cheatsheetseries.owasp.org/cheatsheets/Docker_Security_Cheat_Sheet.html#rule-1-do-not-expose-the-docker-daemon-socket-even-to-the-containers
  category: security
  technology:
  - docker-compose
  cwe:
  - 'CWE-250: Execution with Unnecessary Privileges'
  owasp:
  - A06:2017 - Security Misconfiguration
  - A05:2021 - Security Misconfiguration
  subcategory:
  - audit
  likelihood: LOW
  impact: HIGH
  confidence: LOW
  license: Commons Clause License Condition v1.0[LGPL-2.1-only]
  vulnerability_class:
  - Improper Authorization
  source: https://semgrep.dev/r/yaml.docker-compose.security.exposing-docker-socket-volume.exposing-docker-socket-volume
  shortlink: https://sg.run/O14b
  semgrep.dev:
    rule:
      r_id: 10131
      rv_id: 111109
      rule_id: eqUvZ9
      version_id: K3TvG8r
      url: https://semgrep.dev/playground/r/K3TvG8r/yaml.docker-compose.security.exposing-docker-socket-volume.exposing-docker-socket-volume
      origin: community
languages:
- yaml
severity: WARNING
