id: yaml.github-actions.semgrep-configuration.semgrep-github-action-push-without-branches.semgrep-github-action-push-without-branches
message: The 'branches' field (in the push event configuration) contains no branches.
  This causes all branches to be scanned and may result in unneccessary duplicate
  findings across the entire codebase.
severity: WARNING
languages:
- yaml
paths:
  include:
  - .github/workflows/semgrep.yml
  - '*.test.yml'
patterns:
- pattern-either:
  - pattern: 'on: [..., push, ...]

      ...

      '
  - pattern: 'on: push

      ...

      '
  - pattern: "on:\n  ...\n  push: \"\"\n  ...\n...\n"
  - pattern: "on:\n  ...\n  push: {}\n  ...\n...\n"
  - patterns:
    - pattern-inside: "on:\n  ...\n  push: ...\n  ...\n...\n"
    - pattern-either:
      - pattern: 'branches: ""

          '
      - pattern: 'branches: []

          '
metadata:
  category: correctness
  technology:
  - github-action
  license: Commons Clause License Condition v1.0[LGPL-2.1-only]
  source: https://semgrep.dev/r/yaml.github-actions.semgrep-configuration.semgrep-github-action-push-without-branches.semgrep-github-action-push-without-branches
  shortlink: https://sg.run/GOBn
  semgrep.dev:
    rule:
      r_id: 14648
      rv_id: 111122
      rule_id: GdUrOG
      version_id: yeTRZGz
      url: https://semgrep.dev/playground/r/yeTRZGz/yaml.github-actions.semgrep-configuration.semgrep-github-action-push-without-branches.semgrep-github-action-push-without-branches
      origin: community
